{ lib, config, ... }:
let
  theme = config.theme;

  whitespace-left-prompt =
      let ws = theme.whitespace; in
      if (lib.isString ws) then ws else ws.left-elements;
  whitespace-right-prompt =
      let ws = theme.whitespace; in
      if (lib.isString ws) then ws else ws.right-elements;

  getLeftValue = opt: lib.attrByPath ["left"] opt opt;
  getRightValue = opt: lib.attrByPath ["right"] opt opt;

  isEnabled = name: (lib.elem name theme.left-prompt) || (lib.elem name theme.right-prompt);
in
''
# AUTO-GENERATED!
# This file was generated by the zsh-powerlevel10k nix module, change its
# options rather than edit this file. If you just want to fast-iterate on
# little tweaks, you can just `export POWERLEVEL9K_FOO=bar` and `p10k reload`.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Defines character set used by powerlevel10k. It's best to let `p10k configure` set it for you.
  typeset -g POWERLEVEL9K_MODE=${theme.mode}

  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    ${lib.join " " (map (lib.replaceStrings ["-"] ["_"]) theme.left-prompt)}
  )

  # The list of segments shown on the right. Fill it with less important segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    ${lib.join " " (map (lib.replaceStrings ["-"] ["_"]) theme.right-prompt)}
  )

  # general prompt background
  typeset -g POWERLEVEL9K_BACKGROUND="${toString theme.background}"

  # Spacing around each prompt element; LEFT_RIGHT means left prompt, right side of the element
  typeset -g POWERLEVEL9K_RIGHT_RIGHT_WHITESPACE="${getRightValue whitespace-right-prompt}"
  typeset -g POWERLEVEL9K_RIGHT_LEFT_WHITESPACE="${getLeftValue whitespace-right-prompt}"
  typeset -g POWERLEVEL9K_LEFT_RIGHT_WHITESPACE="${getRightValue whitespace-left-prompt}"
  typeset -g POWERLEVEL9K_LEFT_LEFT_WHITESPACE="${getLeftValue whitespace-left-prompt}"

  # Separator between same-color prompt element
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="${getRightValue theme.subsegment-separator}"
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="${getLeftValue theme.subsegment-separator}"
  # Separator between different-color prompt element
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="${getRightValue theme.segment-separator}"
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="${getLeftValue theme.segment-separator}"

  # General expression to use for displaying prompt icons
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${theme.icons-expression}'

  ${if isEnabled "prompt-char" then let opts = theme.prompt-char; in ''
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND="${opts.ok.foreground}"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND="${opts.error.foreground}"
    typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='${opts.symbol}'
  '' else ""}

  ${if isEnabled "dir" then let opts = theme.dir; in ''
    typeset -g POWERLEVEL9K_DIR_BACKGROUND="${toString opts.background}"
    typeset -g POWERLEVEL9K_DIR_FOREGROUND="${toString opts.foreground}"

    typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="${opts.shorten.strategy}"
    typeset -g POWERLEVEL9K_SHORTEN_DELIMITER="${opts.shorten.delimiter}"
    typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=${toString opts.shorten.length}

    typeset -g POWERLEVEL9K_DIR_PATH_ABSOLUTE=${lib.boolToString opts.absolute}
    typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=${lib.boolToString opts.writable}

    typeset -g POWERLEVEL9K_DIR_CONTENT_EXPANSION='${opts.expression}'
  '' else ""}

  ${if isEnabled "vcs" then let opts = theme.vcs; in ''
    typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND="${toString opts.loading-foreground}"
    typeset -g POWERLEVEL9K_VCS_FOREGROUND="${toString opts.foreground}"
    typeset -g POWERLEVEL9K_VCS_BACKGROUND="${toString opts.background}"

    typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${opts.expression}'
    typeset -g POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${opts.loading-expression}'

    ${if (opts.formatter == null) then "" else ''
      typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
      function my_git_formatter() {
        ${opts.formatter}
      }
      functions -M my_git_formatter 2>/dev/null
    ''}
  '' else ""}

  # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
  # For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
  # can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
  # really need it.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=${toString theme.instant-prompt}

  # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
  # For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
  # can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
  # really need it.
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=${lib.boolToString (!theme.hot-reload)}

  # If p10k is already loaded, reload configuration.
  # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
  (( ! $+functions[p10k] )) || p10k reload

  ${theme.extraConfig}
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=''${''${(%):-%x}:a}

(( ''${#p10k_config_opts} )) && setopt ''${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'

${config.extraConfig}
''